version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: tpmra
      POSTGRES_PASSWORD: tpmra
      POSTGRES_DB: apidb
    ports:
      - "5432:5432"

  tpmra: 
    build: .
    image: jaguesse/tpmra
    container_name: tpmra
    ports: 
      - "8080:8080"